# Site settings
title: AutoPros Mobile Detailing

tagline: "Premier Car, Auto Mobile Detailing & Wash in Tampa"
# tagline: "Never drive a dirty vehicle again!"

description: > # Is your vehicle in need of a car wash?
  Do you need some auto detailing done but you simply just don't have the time?
  Auto Pros Mobile makes getting auto done easy.

baseurl: "/autopros" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

email: info@autoprosmobile.com
facebook: AutoProsMobile
twitter: AutoProsDetail

collections:
   services:
      output: true

# Build settings
markdown: kramdown
permalink: pretty
# permalink: /:categories/:title/

paginate: 10
paginate_path: "/blog/page:num"
paginate_category: blog

gems:
 - jekyll-coffeescript
 - jekyll-paginate
